# application.yml
server:
  port: ${PORT:0}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true